version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root


#   git remote add origin <repository-url>
# git branch -M main  # Use "main" if your default branch is named "main" or "master" for older repositories.
# git commit -m "Initial commit"
# git push -u origin main  # Replace "main" with "master" if you're using an older repository with the "master" branch.

